name: 'Action-SSH'
description: ' Simple GitHub Action to run commands on a remote server using SSH.'
author: 'tiyee'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  command:
    description: "Command to execute on the remote server."
    required: true
  host:
    description: "Hostname or IP address of the server."
    required: true
  username:
    description: "Username for authentication."
    required: true
  port:
    description: "Port number of the server."
    required: false
    default: "22"
  privateKey:
    description: "File  string that contains a private key for either key-based or hostbased user authentication (OpenSSH format)"
    required: true

runs:
  using: node20
  main: dist/index.js
